# Generated by Django 5.1.6 on 2025-04-17 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_rename_created_at_order_order_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_location', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('optimized_route', models.TextField()),
                ('estimated_time', models.DurationField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.order')),
            ],
        ),
    ]
