# Generated by Django 5.1.6 on 2025-04-18 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
        ('users', '0007_customuser_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logistics',
            name='id',
        ),
        migrations.AddField(
            model_name='logistics',
            name='distance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='logistics',
            name='order_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.order'),
        ),
    ]
