# Generated by Django 5.1.6 on 2025-04-24 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_remove_logistics_id_logistics_distance_and_more'),
        ('users', '0022_alter_product_supplier_alter_warehouse_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logistics',
            name='start_location',
        ),
        migrations.AddField(
            model_name='logistics',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logistics', to='users.warehouse'),
        ),
    ]
