# Generated by Django 5.1.6 on 2025-04-18 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_supplier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
