# Generated by Django 5.1.6 on 2025-04-20 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_warehouse_product_id_warehouse_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='product',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='users.product'),
        ),
    ]
