# Generated by Django 5.1.6 on 2025-04-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_supplier_rating_alter_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierrating',
            name='order',
        ),
        migrations.RemoveField(
            model_name='supplierrating',
            name='supplier',
        ),
        migrations.AddField(
            model_name='order',
            name='supplier_rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.DeleteModel(
            name='ProductRating',
        ),
        migrations.DeleteModel(
            name='SupplierRating',
        ),
    ]
