# Generated by Django 5.1.6 on 2025-04-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_order_supplier_rating_supplier_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
