# Generated by Django 5.1.6 on 2025-04-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_order_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('low_stock', 'Low Stock Alert'), ('critical_stock', 'Critical Stock Alert'), ('empty_stock', 'Empty Stock Alert'), ('order_update', 'Order Update')], default='low_stock', max_length=20),
        ),
    ]
